services:
  server:
    build:
      context: .
      dockerfile: ./docker/nginx-dev/Dockerfile
    volumes:
      - ./:/app
      - static_volume:/app/static
    environment:
      - TZ=America/New_York

      # Uncomment RUNNING_WITH_DATE_STRING and DATE_STRING if using a String to represent
      # the current date. DATE_STRING MUST have the format YYYY-MM-DD and be within the 
      # past 30 days (intended to be the date of the last CSV file in the data directory). 
      # If formatted improperly, datetime.now().date() will be used. If commented, 
      # datetime.now().date() will be used to represent the current date.
      
      - RUNNING_WITH_DATE_STRING=True
      - DATE_STRING=2024-07-07
    expose:
      - 5000
    command: /bin/bash -c "cron && gunicorn --bind 0.0.0.0:5000 app:app"

  nginx:
    build: ./nginx-local
    volumes:
      - static_volume:/app/static
      - ./nginx-local/nginx-templates:/etc/nginx/templates
    environment:
      # Change path to staticfiles here
      # https://github.com/docker-library/docs/tree/master/nginx#using-environment-variables-in-nginx-configuration-new-in-119
      - STATIC_FILE_PATH=/app/static/
    ports:
      - 1337:80
    depends_on:
      - server

volumes:
  static_volume:

