services:
  server:
    build:
      context: .
      dockerfile: ./docker/local-dev/Dockerfile
    volumes:
      - ./:/app
    environment:
      - TZ=America/New_York
    ports:
      - 5000:5000
    command: /bin/bash -c "cron && flask --app app run --host=0.0.0.0"